apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-jib-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cicd-jib-pod
  template:
    metadata:
      labels:
        component: cicd-jib-pod
    spec:
      containers:
        - name: cicd-jib-ctn
          image: longdd90jp/sample-cicd-java:0.2
          ports:
            - containerPort: 8085
          env:
            - name: SERVICES
              value: cicd-jib-svc
          envFrom:
            - configMapRef:
                name: microservice-cm