apiVersion: v1
kind: Service
metadata:
  name: cicd-jib-svc
  labels:
    component: cicd-jib-svc
spec:
  type: ClusterIP
  selector:
    component: cicd-jib-pod
  ports:
    - port: 8085
      targetPort: 8085
