apiVersion: v1
kind: PersistentVolume
metadata:
  name: source-code-pv
  labels:
    name: source-code-pv
spec:
  storageClassName: source-code-pv-manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv1001/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tekton-workspace
  labels:
    name: tekton-workspace
spec:
  storageClassName: source-code-pv-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1.5Gi
